version: '3.0'
services:
  db-books-api:
    env_file:
      - .env
    image: 'postgres:17.2-alpine3.21'
    restart: always
    ports:
      - '5444:5432'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}