spring:
  datasource:
    url: jdbc:postgresql://localhost:5444/${POSTGRES_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
