spring:
  datasource:
    url: jdbc:postgresql://localhost:5444/${POSTGRES_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update  # or 'create' for first create tables
  flyway:
    enabled: true
    locations: classpath:db/migration


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
